# Generated by Django 3.2.8 on 2021-10-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_url',
            field=models.CharField(max_length=2560, verbose_name='이미지주소'),
        ),
    ]
